name: "Update Version Packages"

on:
  push:
    branches:
      - "master"

permissions:
  contents: write

jobs:
  bump-version:
    name: "Update Version Packages"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v4"
        with:
          ref: ${{ github.ref }}

      # Read package.json
      - name: "Read package.json"
        run: echo ::set-output name=package_json::$(cat ./package.json)
        id: read-package-json

      - name: "Setup Node.js"
        uses: "actions/setup-node@v4"
        with:
          node-version: 18

      - name: "Install pnpm"
        uses: pnpm/action-setup@v2.4.0

      # Install dependencies
      - name: "Install dependencies"
        run: pnpm install

      # Update packages with pnpm
      - name: "PNPM update latest"
        run: pnpm up --latest

      # Write updated package.json
      - name: "Write package.json"
        run: echo "${{ steps.read-package-json.outputs.package_json }}" > ./package.json

      # Check if pnpm-lock.yaml needs update
      - name: "Check pnpm-lock.yaml changes"
        run: |
          git diff --exit-code --name-only || {
            echo "pnpm-lock.yaml changed. Committing changes..."
            git add pnpm-lock.yaml
            git commit -m "chore: update pnpm-lock.yaml" || true
          }

      # Display updated package.json
      - name: "cat package.json"
        run: cat ./package.json
